$ ->
  if $('.pagination').length && $('#bodypost').length
    $(window).scroll ->
      url = $('.pagination .next_page').attr('href')
      if url && $(window).scrollTop() > $(document).height() - $(window).height() - 50
        $('.pagination').text("Mostrando más posts...")
        $.getScript(url)
    $(window).scroll()

$ ->
  #nav
  closeSearch = ->
    $('.search-field').val ''
    $('.search-field').hide()
    $('#search-nav').removeClass 'active'
    $('#search-nav button[type="reset"]').hide()
    return

  openSearch = ->
    $('#search-nav').addClass 'active'
    $('.search-field').show()
    $('.search-field').focus()
    $('#search-nav button[type="reset"]').show()
    return

  $('#BB-nav').affix offset: top: $('header').height()
  #search form
  #close on escape key
  $(document).keyup (e) ->
    if e.which == 27
      closeSearch()
    return
  # Show Search if form is not active or input search empty
  $('#search-nav button[type="submit"]').click (event) ->
    if !$('#search-nav').hasClass('active') or $('.search-field').val() == ''
      event.preventDefault()
      openSearch()
    return
  #close form
  $('#search-nav button[type="reset"]').click (event) ->
    #event.preventDefault();
    closeSearch()
    return
  return

# ---
# generated by js2coffee 2.2.0